#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2024-2026 The XTC Project Authors
#
__all__ = [
    "squeezenet_convs",
    "alexnet_convs",
    "alexnet_matmuls",
]

squeezenet_convs = {
    "SqueezeNet_00": {
        "n": 1,
        "h": 224,
        "w": 224,
        "c": 3,
        "r": 7,
        "s": 7,
        "f": 96,
        "strx": 2,
        "stry": 2,
    },
    "SqueezeNet_01": {
        "n": 1,
        "h": 54,
        "w": 54,
        "c": 96,
        "r": 1,
        "s": 1,
        "f": 16,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_03": {
        "n": 1,
        "h": 56,
        "w": 56,
        "c": 16,
        "r": 3,
        "s": 3,
        "f": 64,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_04": {
        "n": 1,
        "h": 54,
        "w": 54,
        "c": 128,
        "r": 1,
        "s": 1,
        "f": 16,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_05": {
        "n": 1,
        "h": 54,
        "w": 54,
        "c": 128,
        "r": 1,
        "s": 1,
        "f": 32,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_07": {
        "n": 1,
        "h": 54,
        "w": 54,
        "c": 32,
        "r": 3,
        "s": 3,
        "f": 128,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_08": {
        "n": 1,
        "h": 27,
        "w": 27,
        "c": 256,
        "r": 1,
        "s": 1,
        "f": 32,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_11": {
        "n": 1,
        "h": 27,
        "w": 27,
        "c": 256,
        "r": 1,
        "s": 1,
        "f": 48,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_13": {
        "n": 1,
        "h": 27,
        "w": 27,
        "c": 48,
        "r": 3,
        "s": 3,
        "f": 192,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_14": {
        "n": 1,
        "h": 27,
        "w": 27,
        "c": 384,
        "r": 1,
        "s": 1,
        "f": 48,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_17": {
        "n": 1,
        "h": 27,
        "w": 27,
        "c": 64,
        "r": 3,
        "s": 3,
        "f": 256,
        "strx": 1,
        "stry": 1,
    },
    "SqueezeNet_21": {
        "n": 1,
        "h": 15,
        "w": 15,
        "c": 512,
        "r": 1,
        "s": 1,
        "f": 1000,
        "strx": 1,
        "stry": 1,
    },
}

alexnet_convs = {
    "AlexNet_00": {
        "n": 1,
        "h": 228,
        "w": 228,
        "c": 3,
        "r": 11,
        "s": 11,
        "f": 64,
        "strx": 4,
        "stry": 4,
    },
    "AlexNet_01": {
        "n": 1,
        "h": 31,
        "w": 31,
        "c": 64,
        "r": 5,
        "s": 5,
        "f": 192,
        "strx": 1,
        "stry": 1,
    },
    "AlexNet_02": {
        "n": 1,
        "h": 15,
        "w": 15,
        "c": 192,
        "r": 3,
        "s": 3,
        "f": 384,
        "strx": 1,
        "stry": 1,
    },
    "AlexNet_03": {
        "n": 1,
        "h": 15,
        "w": 15,
        "c": 384,
        "r": 3,
        "s": 3,
        "f": 256,
        "strx": 1,
        "stry": 1,
    },
    "AlexNet_04": {
        "n": 1,
        "h": 15,
        "w": 15,
        "c": 256,
        "r": 3,
        "s": 3,
        "f": 256,
        "strx": 1,
        "stry": 1,
    },
}
alexnet_matmuls = {
    "AlexNet_FC6": {"i": 1, "j": 4096, "k": 9216},
    "AlexNet_FC7": {"i": 1, "j": 4096, "k": 4096},
    "AlexNet_FC8": {"i": 1, "j": 1000, "k": 4096},
}
